# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzazi', '0002_auto_20190619_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.jpeg', upload_to='profiles/'),
        ),
    ]
